# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('birthdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
