# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 09:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='login',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='password',
        ),
        migrations.AddField(
            model_name='accounts',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='activation_key',
            field=models.CharField(default='12345test', max_length=50),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
