# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160311_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
